### ISSUE TITLE
How to raise a message on rust side?

### ISSUE THREAD

**Issue by oovm** [WolframResearch/wolfram-library-link-rs#37]
For example how to call

```wolfram
Message[f::argx, 1, 2]
```

I mean, displayed during calculation, not as calculation result

**Comment by ConnorGray** [comment]
Thank you for raising this issue.

I've added a [new piece of 'How To' documentation](https://docs.rs/wolfram-library-link/latest/wolfram_library_link/docs/evaluate_wolfram_code_from_rust/index.html) that covers the general question of how to perform Wolfram evaluations from within Rust LibraryLink code, and specifically answers the question of how to generate a `Message[..]`.

[**How To: Evaluate Wolfram code from Rust**](https://docs.rs/wolfram-library-link/latest/wolfram_library_link/docs/evaluate_wolfram_code_from_rust/index.html) 

Please let me know if this information is helpful to you, or if you have any further questions or suggestions.
