### ISSUE TITLE
WSTP Examples do not run

### ISSUE THREAD

**Issue by mrektor** [WolframResearch/wolfram-library-link-rs#63]
While it seems that the type-specific functions do run well:

```rust
#[export]
fn square(x: i64) -> i64 {
    x * x
}
```

```Wolfram
In[1]:= s = 
 LibraryFunctionLoad[
  "<path>/target/release/libwolframbind.dylib", "square", {Integer}, Integer]

Out[1]= LibraryFunction["<path>/target/release/libwolframbind.dylib", "square", {Integer}, Integer]

In[2]:= s[100]

Out[2]= 10000
```

When I try to run:

wolfram-library-link/examples/wstp.rs

It compiles with no problem but in the Wolfram Language session I get:

```
In[14]:= load = 
 LibraryFunctionLoad[
  "<path>/target/release/libwolframbind.dylib", "load_wstp_functions", LinkObject, 
  LinkObject]

Out[14]= \
LibraryFunction["<path>/target/release/libwolframbind.dylib", "load_wstp_functions", LinkObject]

In[15]:= functions = load["libwstp_example"]

During evaluation of In[15]:= LibraryFunction::noopen: Cannot open libwstp_example.

During evaluation of In[15]:= LibraryFunction::noopen: Cannot open libwstp_example.

During evaluation of In[15]:= LibraryFunction::noopen: Cannot open libwstp_example.

During evaluation of In[15]:= General::stop: Further output of LibraryFunction::noopen will be suppressed during this calculation.

Out[15]= <|"total" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), 
 "expr_string_join" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), 
 "link_expr_identity" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), 
 "string_join" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), 
 "total_args_i64" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), 
 "count_args" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), 
 "square_wstp" -> (Block[{$Context = 
       "RustLinkWSTPPrivateContext`", $ContextPath = {}}, \
$Failed[##1]] &), "square" -> $Failed|>
```

Do you have any idea of what to do?

for context I'm using:

```
[lib]
crate-type = ["cdylib"]

[dependencies]
wolfram-library-link = "0.2.10"
```

And Wolfram 14.0

**Comment by ConnorGray** [comment]
I think this line needs to be updated, since you're intending to load your own library, not the WSTP examples library:

```
In[15]:= functions = load["libwstp_example"]
```

**Comment by ConnorGray** [comment]
This [example from the docs](https://docs.rs/wolfram-library-link/0.2.10/wolfram_library_link/macro.generate_loader.html#:~:text=Instead%20of%20writing%20three%20separate%20LibraryFunctionLoad%20calls%2C%20one%20for%20each%20exported%20function%2C%20you%20can%20instead%20load%20the%20single%20load_my_library_functions%20function%2C%20which%2C%20when%20called%2C%20will%20automatically%20load%20the%20other%20three%20functions%20exported%20by%20this%20library%3A) I believe shows the right thing to do, though it specifically shows using only the library name "example_library", not the full file path; but both can work, using the full path is just more reliable.

You should pass the full library path (`"/Users/ettore/<snip>/libwolframbind.dylib"`) both to `LibraryFunctionLoad` and the `load` function.

**Comment by mrektor** [comment]
It works! thank you very much :)
